#!/usr/bin/env python

import subprocess
from pprint import pprint
import requests
import json
import base64
import webbrowser


api_key = "6f0575d73f8c30f"
url = r'https://api.imgur.com/3/upload.json'

subprocess.call("scrot")
img = subprocess.check_output("ls -t | head -1", shell=True).strip()
f = open(img, 'rb')

binary_data = f.read()
b64image = base64.b64encode(binary_data)

headers = {'Authorization' : 'Client-ID ' + api_key}
payload = {'key' : api_key, 'image' : b64image, 'title' : 'scrot',}

r = requests.post(url, headers=headers, data=payload)

j = json.loads(r.text)
link = j['data']['link']

webbrowser.open(link)

subprocess.call("rm " + img, shell=True)




